[package]
name = "mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mesh-core = { path = "../mesh-core" }
mesh-ledger = { path = "../mesh-ledger" }
mesh-protocol = { path = "../mesh-protocol" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
